a1=int(input("enter 1st denomination: "))
a2=int(input("enter no .of notes for 1st denomination: "))
b1=int(input("enter 2nd denomination: "))
b2=int(input("enter no .of notes for 2nd denomination: "))
c1=int(input("enter 3rd denomination: "))
c2=int(input("enter no .of notes for 3rd denomination: "))
d1=int(input("enter 2nd denomination: "))
d2=int(input("enter no .of notes for 1st denomination: "))
totalamount=a1*a2+b1*b2+c1*c2+d1*d2
print("Total amount: ",totalamount)
